### ISSUE TITLE
PlayerInventory#getOwner NPE

### ISSUE THREAD

**Issue by 100chilly** [MassiveCraft/MassiveBooks#7]
I'm using spigot-1.9 updated moments ago as well as the latest beta package of massviecore and it errors out when i run the book give command.
`[08:42:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'book give 100chilly 1 questsguide' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(book)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1342) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1177) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_9_R1.PlayerInventory.getOwner(PlayerInventory.java:54) ~[spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventoryPlayer.getHolder(CraftInventoryPlayer.java:207) ~[spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:67) ~[spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventoryPlayer.setHelmet(CraftInventoryPlayer.java:132) ~[spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        at com.massivecraft.massivecore.util.InventoryUtil.cloneInventory(InventoryUtil.java:381) ~[?:?]
        at com.massivecraft.massivecore.util.InventoryUtil.roomLeft(InventoryUtil.java:478) ~[?:?]
        at com.massivecraft.massivebooks.cmd.CmdBookGive.perform(CmdBookGive.java:75) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:895) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:852) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:936) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-7e9e6eb-1fefbf9]
        ... 14 more
`
Any fixes would be greatly appericated. :smile:

**Comment by 100chilly** [comment]
Also here is output of the version via console.
`[08:50:35 INFO]: This server is running CraftBukkit version git-Spigot-7e9e6eb-1fefbf9 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
[08:50:35 INFO]: Checking version, please wait...
[08:50:36 INFO]: You are running the latest version`

**Comment by Devillion** [comment]
This is what I get for the same issue, when trying to give a book to a player: http://i.imgur.com/og4868G.png

i haven't really tried anything else yet.

**Comment by oloflarsson** [comment]
It is fixed since 2.8.8.
